name: 'ROS 2 Lint Action'
description: 'Run ROS 2 Linters using Github Actions.'
author: 'ROS 2 Tooling Working Group'
branding:
  icon: 'thermometer'
  color: 'green'
inputs:
  linter:
    default: 'flake8'
    description: 'ROS 2 Linter'
    required: false
  distribution:
    default: 'eloquent'
    description: 'ROS 2 Distribution to install the lint tool from'
    required: false
  package-name:
    description: |
        Name of the package(s) under test, as expected by colcon.
        Passing multiple package names is allowed.
        Package names can be separated by any whitespace character.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
