name: "Test action-ros-lint"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  schedule:
    # Run the CI automatically every hour to look for flakyness.
    - cron:  '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
    - uses: actions/checkout@v2
      with:
        path: '.'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - uses: ros-tooling/setup-ros@0.0.16
    - uses: actions/checkout@v2
      with:
        repository: ament/ament_lint
        ref: 0.8.1
        path: 'ament_lint'
    - name: Try default linter
      uses: ./
      with:
        package-name: ament_copyright ament_lint
        workspace-directory: ament_lint
    - name: Try a linter with underscores in the name
      uses: ./
      with:
        linter: lint_cmake
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint
