name: "Test action-ros-lint"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  schedule:
    # Run the CI automatically every hour to look for flakyness.
    - cron:  '0 * * * *'

jobs:
  test_setup_ros:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
    - uses: actions/checkout@v4
      with:
        path: '.'
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: .github/workflows/build-and-test.sh
    - uses: ros-tooling/setup-ros@v0.7
    - uses: actions/checkout@v4
      with:
        repository: ament/ament_lint
        ref: humble
        path: 'ament_lint'
    - name: Try default linter
      uses: ./
      with:
        package-name: ament_copyright ament_lint
        workspace-directory: ament_lint
    - name: Try a linter with additional arguments
      uses: ./
      with:
        linter: lint_cmake
        arguments: '--filter=-linelength,+syntax'
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint
    - name: Try a linter with underscores in the name
      uses: ./
      with:
        linter: lint_cmake
        arguments: '--filter=-linelength'
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint

  test_setup_ros_docker:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: '.'
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: .github/workflows/build-and-test.sh
    - uses: actions/checkout@v4
      with:
        repository: ament/ament_lint
        ref: humble
        path: 'ament_lint'
    - name: Try default linter
      uses: ./
      with:
        package-name: ament_copyright ament_lint
        workspace-directory: ament_lint
    - name: Try a linter with additional arguments
      uses: ./
      with:
        linter: lint_cmake
        arguments: '--filter=-linelength,+syntax'
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint
    - name: Try a linter with underscores in the name
      uses: ./
      with:
        linter: lint_cmake
        arguments: '--filter=-linelength'
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint
