name: "Test action-ros-lint"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  schedule:
    # Run the CI automatically every hour to look for flakyness.
    - cron:  '0 * * * *'

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test_setup_ros:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
    - uses: actions/checkout@v3.6.0
      with:
        path: '.'
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '16.x'
    - run: .github/workflows/build-and-test.sh
    - uses: ros-tooling/setup-ros@0.7.4
    - uses: actions/checkout@v3.6.0
      with:
        repository: ament/ament_lint
        ref: 0.9.8
        path: 'ament_lint'
    - name: Try default linter
      uses: ./
      with:
        package-name: ament_copyright ament_lint
        workspace-directory: ament_lint
    - name: Try a linter with additional arguments
      uses: ./
      with:
        linter: lint_cmake
        arguments: '--filter=-linelength,+syntax'
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint
    - name: Try a linter with underscores in the name
      uses: ./
      with:
        linter: lint_cmake
        arguments: '--filter=-linelength'
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint

  test_setup_ros_docker:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-latest
      options: -u root  # setup-node requires root access
    steps:
    - uses: actions/checkout@v3.6.0
      with:
        path: '.'
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '16.x'
    - run: .github/workflows/build-and-test.sh
    - uses: actions/checkout@v3.6.0
      with:
        repository: ament/ament_lint
        ref: 0.9.8
        path: 'ament_lint'
    - name: Try default linter
      uses: ./
      with:
        package-name: ament_copyright ament_lint
        workspace-directory: ament_lint
    - name: Try a linter with additional arguments
      uses: ./
      with:
        linter: lint_cmake
        arguments: '--filter=-linelength,+syntax'
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint
    - name: Try a linter with underscores in the name
      uses: ./
      with:
        linter: lint_cmake
        arguments: '--filter=-linelength'
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint
