name: "Test action-ros-lint"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  schedule:
    # Run the CI automatically every hour to look for flakyness.
    - cron:  '0 * * * *'

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test_setup_ros:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
    - uses: actions/checkout@v2
      with:
        path: '.'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: .github/workflows/build-and-test.sh
    - uses: ros-tooling/setup-ros@0.0.19
    - uses: actions/checkout@v2
      with:
        repository: ament/ament_lint
        ref: 0.8.1
        path: 'ament_lint'
    - name: Try default linter
      uses: ./
      with:
        package-name: ament_copyright ament_lint
        workspace-directory: ament_lint
    - name: Try a linter with underscores in the name
      uses: ./
      with:
        linter: lint_cmake
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      if: always()
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      if: always()

  test_setup_ros_docker:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-bionic-ros-eloquent-ros-base-latest
      options: -u root  # setup-node requires root access
    steps:
    - run: sudo chown -R rosbuild:rosbuild .
    - uses: actions/checkout@v2
      with:
        path: '.'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: .github/workflows/build-and-test.sh
    - uses: actions/checkout@v2
      with:
        repository: ament/ament_lint
        ref: 0.8.1
        path: 'ament_lint'
    - name: Try default linter
      uses: ./
      with:
        package-name: ament_copyright ament_lint
        workspace-directory: ament_lint
    - name: Try a linter with underscores in the name
      uses: ./
      with:
        linter: lint_cmake
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      if: always()
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      if: always()
